### PR TITLE
change awk to mawk

### PR DESCRIPTION
**Pull request by shmick**

### CODE REVIEW

**Comment by socram8888** [comment]
Why is this PR needed. Isn't it working correctly with GNU awk and it therefore needs to explicitely target mawk?

**Comment by shmick** [comment]
Hi,

Sorry for the lack of info. On my Raspberry Pi running gnu awk 4.1.1, the get_domain function only returns the TLD, not the domain name. When I switch it to mawk, I end up with the domain name.

**Comment by socram8888** [comment]
Instead of forcing the user to install a certain version of awk, I'd like to figure out why it doesn't work in gawk if it's supposed to support a superset of the older mawk.

I'll keep this open until I've figured out why.

**Comment by shmick** [comment]
My awk-foo isn't too strong, but from what I can tell, this `gsub(/^.*\./, "", domain)` line looks to be the culprit.

**Comment by socram8888** [comment]
Apparently it was much simpler. The substr starts at 1, not 0, and apparently that was screwing the domain calculation in line 70.

I've fixed it in commit a52c0331ee32bc50fd306ed673d88cfa53c8e541.

Thanks for pointing this bug out.

**Comment by shmick** [comment]
Excellent. Thanks for the quick fix!

**Pull request closed without merging**
